# 护照阅读器配置文件

WebSocketUri: "ws://127.0.0.1:90/echo"

# 航班时间配置（时：分）
FlightTimes:
  StartHour: 6
  EndHour: 23
  IntervalMinutes: 30

Ports:
  - Code: "SM"
    Name: "福永"
  - Code: "HKG"
    Name: "香港"
  - Code: "MFM"
    Name: "澳门"
  - Code: "SZX"
    Name: "深圳"
  - Code: "SK"
    Name: "深圳蛇口"

DocumentTypes:
  - Code: "EEP"
    Name: "往来港澳通行证"
  - Code: "PASSPORT"
    Name: "外国护照"
  - Code: "HKID"
    Name: "香港身份证"
  - Code: "MOID"
    Name: "澳门身份证"
  - Code: "XGZ"
    Name: "回乡证"
  - Code: "TBP"
    Name: "台胞证"

PopularCountries:
  - Code: "CHN"
    Name: "中国"
  - Code: "USA"
    Name: "美国"
  - Code: "JPN"
    Name: "日本"
  - Code: "KOR"
    Name: "韩国"
  - Code: "THA"
    Name: "泰国"
  - Code: "SGP"
    Name: "新加坡"
  - Code: "MYS"
    Name: "马来西亚"
  - Code: "VNM"
    Name: "越南"
  - Code: "IDN"
    Name: "印度尼西亚"
  - Code: "PHL"
    Name: "菲律宾"
  - Code: "AUS"
    Name: "澳大利亚"
  - Code: "GBR"
    Name: "英国"
  - Code: "FRA"
    Name: "法国"
  - Code: "DEU"
    Name: "德国"
  - Code: "CAN"
    Name: "加拿大"
  - Code: "RUS"
    Name: "俄罗斯"
  - Code: "IND"
    Name: "印度"
  - Code: "PAK"
    Name: "巴基斯坦"
  - Code: "BGD"
    Name: "孟加拉"
  - Code: "LKA"
    Name: "斯里兰卡"
  - Code: "MMR"
    Name: "缅甸"
  - Code: "KHM"
    Name: "柬埔寨"
  - Code: "LAO"
    Name: "老挝"
  - Code: "TWN"
    Name: "台湾"
  - Code: "HKG"
    Name: "中国香港"
  - Code: "MAC"
    Name: "中国澳门"
